export const navItems = [
  { id: '1', navName: 'Home', navURL: '' },
  { id: '2', navName: 'ONEZERO', navURL: '' },
  { id: '3', navName: 'ELEMENTAL', navURL: '' },
  { id: '4', navName: 'GEN', navURL: '' },
  { id: '5', navName: 'ZORA', navURL: '' },
  { id: '6', navName: 'FORGE', navURL: '' },
  { id: '7', navName: 'HUMAN PARTS', navURL: '' },
  { id: '8', navName: 'MARKER', navURL: '' },
  { id: '9', navName: 'SELF', navURL: '' },
  { id: '10', navName: 'TECH', navURL: '' },
  { id: '11', navName: 'HEATED', navURL: '' },
  { id: '12', navName: 'MODUS', navURL: '' },
  { id: '13', navName: 'MORE', navURL: '' },
];
